[workspace]
members = [
    "packages/hangar-cli",
    "packages/hangar-mcp",
    "packages/hangar-server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/lrs-rodrigues/hangar-ia"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
